apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudnativepg-cluster.yaml
  - longhorn-storageclass.yaml
  - timescale-init-sql.yaml
  - backup-cronjob.yaml
  - pgbackrest-config.yaml
  - prometheus-rules.yaml
  - grafana-dashboard.yaml

configMapGenerator:
  - name: timescale-db-config
    envs:
      - timescale-db-environment.env
